bind h run-shell -b "$ZNT_REPO_DIR/doc/znt-tmux.zsh"
set -g mouse on
set -g history-limit 100000
set -g set-clipboard on
set-option -sg escape-time 10
set-option -g focus-events on
set-option -g default-terminal "tmux-256color"
set-option -as terminal-features ",xterm-256color:RGB"
